### PR TITLE
Charleschege xtokens

### PR DESCRIPTION
**Pull request by charleschege**
Pull request as discussed yesterday. The dependency graph is not good so the repo does not compile

### CODE REVIEW

**Comment by drewstone** [comment]
Can you describe what or where you found this messaging pallet? What's the intention?

**Review by drewstone — CHANGES_REQUESTED** [review]
I don't see xtokens integrated into this PR? I also don't follow what this messaging pallet is doing, there's not much documentation or comments.

**Comment by charleschege** [comment]
> Can you describe what or where you found this messaging pallet? What's the intention?

I got this from the orml workshop docs https://github.com/xlc/orml-workshop

this video explains it https://www.crowdcast.io/e/axvfinsv/19

**Comment by charleschege** [comment]
> I don't see xtokens integrated into this PR? I also don't follow what this messaging pallet is doing, there's not much documentation or comments.

I will have to integrate this using the orml master repo since the released version does not have xtokens AFAIK

**Pull request closed without merging**
